### ISSUE TITLE
Initial release?

### ISSUE THREAD

**Issue by herbygillot** [mitsuhiko/when#6]
Would it be possible to cut an initial version of `when`?

**Comment by mitsuhiko** [comment]
What do you mean by that?

**Comment by herbygillot** [comment]
Basically tagging a version in Git so that a release of `when` can be made available. As of right now there are no releases present for `when`: https://github.com/mitsuhiko/when/releases

I'd like to package `when` to add it to MacPorts, but there are no releases or versions of `when` available to do so.

**Comment by mitsuhiko** [comment]
Ah okay. I will tag something off on the weekend probably. I want to make it so it actually builds from source without having to download something from geonames first.

**Comment by mitsuhiko** [comment]
This is now published to crates.io under the name [`when-cli`](https://crates.io/crates/when-cli).

**Comment by herbygillot** [comment]
Thank you @mitsuhiko. `when` is now available via MacPorts: https://ports.macports.org/port/when/
